version: "3.9"

services:
  postgres:
    image: postgres:14.1
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    ports:
      - "5432:5432"

  news-migrate:
    build: .
    image: news-api
    entrypoint: ["news-api", "migrate"]
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  news-clean-postgres:
    image: postgres:14.1
    env_file:
      - .env
    command: psql ${POSTGRES_URL} -c "TRUNCATE TABLE posts;"
    depends_on:
      - news-migrate

  news-server:
    build: .
    image: news-api
    ports:
      - "8080:8080"
    entrypoint: ["news-api", "server"]
    environment:
      HOST: ""
      PORT: 8080
    env_file:
      - .env
    depends_on:
      - postgres
      - news-migrate
