version: "3.9"

services:
  postgres:
    image: postgres:14.1
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  news-migrate:
    build: .
    image: news-api
    command: ["wait-for", "postgres:5432", "--", "news-api", "migrate"]
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  news-server:
    build: .
    image: news-api
    ports:
      - "8080:8080"
    command: ["wait-for", "postgres:5432", "--", "news-api", "server"]
    environment:
      HOST: ""
      PORT: 8080
    env_file:
      - .env
    depends_on:
      - postgres
      - news-migrate
