// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	// Error codes:
	//   - "NOT_FOUND" - not found by id
	//   - "REQUEST_INVALID" - request fields has invalid types
	//   - "ALREADY_EXISTS" - returns when you create something which is already exists in storage
	//   - "INTERNAL_ERROR" - return when service has unexpected error
	Code string `json:"code"`

	// Error message
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// GetAllPostsResponse defines model for GetAllPostsResponse.
type GetAllPostsResponse struct {
	Posts []Post `json:"posts"`
}

// Post defines model for Post.
type Post struct {
	// Embedded struct due to allOf(#/components/schemas/PostData)
	PostData `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/PostMetadata)
	PostMetadata `yaml:",inline"`
}

// PostData defines model for PostData.
type PostData struct {
	// Post content
	Content *string `json:"content,omitempty"`

	// Post title
	Title string `json:"title"`
}

// PostMetadata defines model for PostMetadata.
type PostMetadata struct {
	// Embedded struct due to allOf(#/components/schemas/PostUpdateMetadata)
	PostUpdateMetadata `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// When post was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Post ID
	Id *string `json:"id,omitempty"`
}

// PostUpdateMetadata defines model for PostUpdateMetadata.
type PostUpdateMetadata struct {
	// When post was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PostID defines model for PostID.
type PostID string

// Default defines model for Default.
type Default ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest ErrorResponse

// NotFound defines model for NotFound.
type NotFound ErrorResponse

// CreatePostJSONBody defines parameters for CreatePost.
type CreatePostJSONBody PostData

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody CreatePostJSONBody
