// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves all posts
	// (GET /posts)
	GetAllPosts(w http.ResponseWriter, r *http.Request)
	// Creates a new post
	// (POST /posts)
	CreatePost(w http.ResponseWriter, r *http.Request)
	// Removes post by ID
	// (DELETE /posts/{postID})
	DeletePost(w http.ResponseWriter, r *http.Request, postID PostID)
	// Retrieves post by ID
	// (GET /posts/{postID})
	GetPost(w http.ResponseWriter, r *http.Request, postID PostID)
	// Updates post by ID
	// (PUT /posts/{postID})
	UpdatePost(w http.ResponseWriter, r *http.Request, postID PostID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetAllPosts operation middleware
func (siw *ServerInterfaceWrapper) GetAllPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllPosts(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreatePost operation middleware
func (siw *ServerInterfaceWrapper) CreatePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePost(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postID" -------------
	var postID PostID

	err = runtime.BindStyledParameter("simple", false, "postID", chi.URLParam(r, "postID"), &postID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postID", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, postID)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postID" -------------
	var postID PostID

	err = runtime.BindStyledParameter("simple", false, "postID", chi.URLParam(r, "postID"), &postID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postID", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPost(w, r, postID)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdatePost operation middleware
func (siw *ServerInterfaceWrapper) UpdatePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "postID" -------------
	var postID PostID

	err = runtime.BindStyledParameter("simple", false, "postID", chi.URLParam(r, "postID"), &postID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postID", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePost(w, r, postID)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts", wrapper.GetAllPosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/posts", wrapper.CreatePost)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/posts/{postID}", wrapper.DeletePost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/posts/{postID}", wrapper.GetPost)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/posts/{postID}", wrapper.UpdatePost)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWW2/bNhT+K8TZHpXIXTOg0Js3u4Mxz+6cZBc0gcFIxxYLiVRJyo4R6L8PPJR8k1x3",
	"gBd0bxLJc/u+c3uBWOWFkiitgegFCq55jhY1/X1Qxo4G7itBE2tRWKEkRHTORgMIQLjfgtsUApA8R/fn",
	"hQLQ+LkUGhOIrC4xABOnmHOnbaF0zi1EUJYigQDspnCSxmohl1BVlRM2hZIGyY8BLniZWfcZK2lR0icv",
	"ikzE3PkUfjLOsZc9G99rXEAE34W7AEN/a8Kh1krPagve3mGA9xKfC4wtJsygXqFm6ESgCmAkVzwTyQw/",
	"l2he0aXaLtO14SqAibLvVSmT13NioixbkEl3V4s5rSRJCaRVgdoKT1ysEmynDz1m7s5ED5KxK/YAk+nd",
	"/P30fjJ4AHbFZGOHPW2YSJpHs+Hv98Pbu/lo8kd/PPJPazzYQmCWGJZyw0QNlUsr08j2x7Nhf/D3fPjX",
	"6Pbutha1pZaGrVOUbKNKFmvkFplROdpUyCVbpyJOmTCMZxp5smH4LIx1FpixSvMlNupHk7vhbNIfz4ez",
	"2XS2p95rd1kkYiT3yl1yUVY9yHYJBJCjMXx5Er3mul08+4X30TOw0/ZYBXDIcoszbKg8myktY170ceuT",
	"evqEMaXqL2j7Web6hjlt2XUO+hAWc3POBafMqa5tca35puWRV9nlEYm7asmy6QKij+eNDbjlUAXnH/6G",
	"lif0+JRhUtVRLdsa7ui3zW1HrlhhMzwh5u8CyPnzGOXSphD92AsgF7L5fXsuh7yKU7Fso/1XYN4XCbe4",
	"QypogUG1mMx5Bx5/upJy1LI1N3XVujmynStO95UVOXahJZIvTbRzs6mFwmONw1FELXZLuv+agDJuLKuf",
	"f2VUbbfckZAL5YzV+QETXBvW/zBitzTUIIAVauNdeHPdu+45eFSBkhcCInhLRwHNdwoh3FboEikKFx8N",
	"mlEC0X6Rw9EE/6HXu9iU6uolHbNq+quL5sYb7tK3dTA8mumkartxfFm0WU1oHpZ5zvUGIpih1QJX6AZH",
	"xjxqVUDdqA3bz5S/1I983aGxP6lkczHAds2rvVpdkpjD3vdtMeJBNowziWtihB74jA5f/NJa+crM0GKb",
	"pgGd1zTt78knut3uSVjv0W4cdIF/QZRuejfnxbZ74yUSPVcuzal3PW1cC62Ck93hvwDvYpl78Yx9fS6a",
	"pnPIRlF2sOGn1TdNyPGK8D+nx4dzSA69oFnskT8Mb6xinkEApc4ggtTaIgrDzB2mytjoXe9dL6TN6WiX",
	"0SopY/rZlzVRGBbbq2uJa3MtVMgLEa7ehG6P+ScAAP//Hl+ArQ0QAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
